### ISSUE TITLE
Python bindings broken

### ISSUE THREAD

**Issue by l-behrens-priv** [frankmorgner/openpace#55]
### Expected behaviour

eac.py and chat.py should be importable. 
Using Archlinux, python3.10, Openpace from master branch

### Actual behaviour

`
python3>>> from openpace import chat
File "/usr/local/lib/python3.10/site-packages/openpace/chat.py", line 47, in <module>
    import eac
ModuleNotFoundError: No module named 'eac'`

### Steps to reproduce

1. git clone https://github.com/frankmorgner/openpace.git
2. ./configure --enable-python  
3. make && make install
4. python -c "from openpace import chat"

### Affects also
[virtualsmartcard ](https://github.com/frankmorgner/vsmartcard/tree/master/virtualsmartcard)

`
(venv) λ  venv git:(6-secure-key-exchange) ✗ vicc -t nPA                                                                   
Traceback (most recent call last):
  File "/usr/local/bin/vicc", line 159, in <module>
    vicc = VirtualICC(args.datasetfile, args.type, hostname, args.port,
  File "/usr/local/lib/python3.10/site-packages/virtualsmartcard/VirtualSmartcard.py", line 439, in __init__
    MF, SAM = self.cardGenerator.getCard()
  File "/usr/local/lib/python3.10/site-packages/virtualsmartcard/CardGenerator.py", line 684, in getCard
    self.generateCard()
  File "/usr/local/lib/python3.10/site-packages/virtualsmartcard/CardGenerator.py", line 677, in generateCard
    self.__generate_nPA()
  File "/usr/local/lib/python3.10/site-packages/virtualsmartcard/CardGenerator.py", line 152, in __generate_nPA
    from virtualsmartcard.cards.nPA import nPA_SAM
  File "/usr/local/lib/python3.10/site-packages/virtualsmartcard/cards/nPA.py", line 31, in <module>
    from openpace.chat import CHAT, CVC, PACE_SEC, EAC_CTX
  File "/usr/local/lib/python3.10/site-packages/openpace/chat.py", line 47, in <module>
    import eac
ModuleNotFoundError: No module named 'eac'
`

**Comment by frankmorgner** [comment]
I cannot verify this problems. both versions are loading successfully in python2.7 and python3.8. Note, that you may need to supply the path of the python binary to avoid confusion:
```
./configure --enable-python PYTHON=`which python3`
```

It seems you have modified the files... I'm not an expert in terms of packaging python modules, but chat.py and eac.py should both be placed in `/usr/local/lib/python3.10/site-packages` (no subfolder `openpace`). As consequence, virtualsmartcard is loading it differently...
https://github.com/frankmorgner/vsmartcard/blob/542be2323c36ce9b686c3d89a0b2dab2fa20fc09/virtualsmartcard/src/vpicc/virtualsmartcard/cards/nPA.py#L31

**Comment by l-behrens-priv** [comment]
Thank you for the quick hint. Indeed I renamed the subdirectory and forgot to mention. Pardon me! Nevertheless an import leads to the same Error as depicted in the issue. Is it a problem with my python distribution/ package installation? After the installation openpace resides in site-packages as follows. 

```
λ  site-packages tree
├── OpenPACE-1.1.2-py3.10-linux-x86_64.egg
│   ├── chat.py
│   ├── _eac.cpython-310-x86_64-linux-gnu.so
│   ├── _eac.py
│   ├── eac.py
│   ├── EGG-INFO
│   │   ├── dependency_links.txt
│   │   ├── native_libs.txt
│   │   ├── not-zip-safe
│   │   ├── PKG-INFO
│   │   ├── SOURCES.txt
│   │   └── top_level.txt
│   ├── __init__.py
│   ├── pace_entity.py
│   └── __pycache__
│       ├── chat.cpython-310.pyc
│       ├── _eac.cpython-310.pyc
│       ├── eac.cpython-310.pyc
│       └── pace_entity.cpython-310.pyc
```

this is consistent with the ouput of "make install"

```
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/eac.py to eac.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/chat.py to chat.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/pace_entity.py to pace_entity.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/_eac.py to _eac.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying OpenPACE.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying OpenPACE.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying OpenPACE.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying OpenPACE.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
__pycache__._eac.cpython-310: module references __file__
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
removing '/usr/local/lib/python3.10/site-packages/OpenPACE-1.1.2-py3.10-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python3.10/site-packages/OpenPACE-1.1.2-py3.10-linux-x86_64.egg
Extracting OpenPACE-1.1.2-py3.10-linux-x86_64.egg to /usr/local/lib/python3.10/site-packages
byte-compiling /usr/local/lib/python3.10/site-packages/OpenPACE-1.1.2-py3.10-linux-x86_64.egg/_eac.py to _eac.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/site-packages/OpenPACE-1.1.2-py3.10-linux-x86_64.egg/chat.py to chat.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/site-packages/OpenPACE-1.1.2-py3.10-linux-x86_64.egg/eac.py to eac.cpython-310.pyc
byte-compiling /usr/local/lib/python3.10/site-packages/OpenPACE-1.1.2-py3.10-linux-x86_64.egg/pace_entity.py to pace_entity.cpython-310.pyc

Installed /usr/local/lib/python3.10/site-packages/OpenPACE-1.1.2-py3.10-linux-x86_64.egg
```

I also extend the `PYTHONPATH` to recognize `/usr/local/lib/python3.10/site-packages`
`export PYTHONPATH=/usr/local/lib/python3.10/site-packages`

**Comment by frankmorgner** [comment]
Did you also change LD_LIBRARY_PATH so that libeac.so can be found?

**Comment by l-behrens-priv** [comment]
yes. 
```
λ  echo $LD_LIBRARY_PATH 
/usr/local/lib/
```
also observed that the manual installation as depicted below, produces the expected results. It's just the installation via make, where I encounter the issue.

```
λ  python git:(master) ✗ python -m venv /*****/venv && source /****/venv/bin/activate
(venv) λ  python git:(master) ✗ pwd
/home/****************/openpace/bindings/python

(venv) λ  python git:(master) ✗ python setup.py install
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup, Extension
running install
running build
running build_py
copying eac.py -> build/lib.linux-x86_64-3.10
running build_ext
building '_eac' extension
swigging eac.i to eac_wrap.c
swig -python -modern -outdir . -I./.. -o eac_wrap.c eac.i
Deprecated command line option: -modern. This option is now always on.
SWIG:1: Warning 125: Use of the include path to find the input file is deprecated and will not work with ccache. Please include the path when specifying the input file.
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/home/**********/venv/include -I/usr/include/python3.10 -c eac_wrap.c -o build/temp.linux-x86_64-3.10/eac_wrap.o -g -O2 -I../../src
gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.10/eac_wrap.o -L/usr/lib -o build/lib.linux-x86_64-3.10/_eac.cpython-310-x86_64-linux-gnu.so -L../../src/.libs -leac -lcrypto
running install_lib
copying build/lib.linux-x86_64-3.10/eac.py -> /home/l*************venv/lib/python3.10/site-packages
copying build/lib.linux-x86_64-3.10/_eac.cpython-310-x86_64-linux-gnu.so -> /home/**************/venv/lib/python3.10/site-packages
running install_egg_info
Removing /home/**************/venv/lib/python3.10/site-packages/OpenPACE-1.1.2-py3.10.egg-info
Writing /home/**************/venv/lib/python3.10/site-packages/OpenPACE-1.1.2-py3.10.egg-info

(venv) λ  smartcard git:(6-secure-key-exchange) ✗ tree venv/lib/python3.10/site-packages/ -L 1
venv/lib/python3.10/site-packages/
├── chat.py
├── _distutils_hack
├── distutils-precedence.pth
├── _eac.cpython-310-x86_64-linux-gnu.so
├── eac.py
├── OpenPACE-1.1.2-py3.10.egg-info
├── pace_entity.py
├── pip
├── pip-21.2.4.dist-info
├── pkg_resources
├── __pycache__
├── setuptools
└── setuptools-58.1.0.dist-info
```

**Comment by frankmorgner** [comment]
Closing this issue due to inactivity. Please re-open the ticket if more input is available.
